name: Java CI + Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-jar
          path: target/git-action-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-jar

      - name: Set up SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/key.pem
          chmod 600 ~/.ssh/key.pem
          ssh-keyscan -H ${{ secrets.DO_HOST }} >> ~/.ssh/known_hosts

      - name: Upload JAR to DigitalOcean
        run: |
          scp -i ~/.ssh/key.pem \
            -o UserKnownHostsFile=~/.ssh/known_hosts \
            git-action-0.0.1-SNAPSHOT.jar \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }}:/root/app.jar

      - name: Run app on DigitalOcean
        run: |
          ssh -i ~/.ssh/key.pem \
            -o UserKnownHostsFile=~/.ssh/known_hosts \
            ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} '
              pkill -f "java -jar" || true
              nohup java -Xms64m -Xmx128m -jar /root/app.jar --server.port=3084 > /root/app.log 2>&1 &
            '
